version: '3'

services:
  divolte:
    build:
      context: .
      dockerfile: ./docker/divolte/Dockerfile
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    restart: always
    ports:
      - "8290:8290"
    command: /opt/app/divolte-collector/bin/divolte-collector
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ./data/divolte/divolte-collector.conf:/opt/app/divolte-collector/conf/divolte-collector.conf
      - ./data/divolte/EventRecord.avsc:/opt/app/divolte-collector/conf/EventRecord.avsc
      - ./data/divolte/mapping.groovy:/opt/app/divolte-collector/conf/mapping.groovy
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    restart: always
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "click_stream"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    links:
      - zookeeper
    depends_on:
      - zookeeper
